#! /usr/bin/env python3

from argparse import ArgumentParser, FileType, RawTextHelpFormatter
from pathlib import Path

from truhanen.ddnsclient import Domain, Updater


def main():
    parser = ArgumentParser(formatter_class=RawTextHelpFormatter)
    parser.add_argument(
        'domain_path', type=FileType('r'),
        help=('The file that lists the credentials and the domains to update.\n'
              'See the example.conf file for example.'))
    parser.add_argument('-d', '--dry-run', action='store_true', dest='dry',
                        help='Dry-run. Don\'t really request any IP updates, only check.')

    args = parser.parse_args()
    dry_run = args.dry
    domain_path = Path(args.domain_path.name)

    domains = Domain.read_from_file(domain_path)
    updater = Updater(domains, dry_run=dry_run)
    updater.run()


if __name__ == '__main__':
    main()
